### PR TITLE
Comment out console.log

### PR DESCRIPTION
**Pull request by satchit8**
Perhaps this will lead to less clutter in our consoles.

### CODE REVIEW

**Comment by nbeloglazov** [comment]
processing.js is copied without modifications from original processing.js repo. So the next release will overwrite your changes anyway. You should submit pull request here instead: https://github.com/processing-js/processing-js

**Comment by satchit8** [comment]
Thanks for the consideration.  I'll give it some thought.

**Comment by craigmalone** [comment]
I submitted an issue for this to https://github.com/processing-js/processing-js (https://github.com/processing-js/processing-js/issues/275#issuecomment-274201931).

It has now been fixed in processing.js 1.6.4, so next update to this library should pick it up.

**Comment by nbeloglazov** [comment]
Thanks Craig. I'll do a new release soon. There also was a new release of processing itself so good time to cut a release.

**Comment by nbeloglazov** [comment]
Released quil 2.6.0 and the issue should be fixed. Thanks @satchit8 and @craigmalone for bringing the issue up and following through with processing.js!

**Pull request closed without merging**
